In [1]:
# **** print a message ****
test = "Hello World !!!"
print("test: " + test)

test: Hello World !!!


In [2]:
# **** print a variable ****
val = 1.2
print(val)
print("val: " + str(val))

1.2
val: 1.2


In [3]:
import math

# **** basic sigmoid function definition ****
def basic_sigmoid(x):
    s = 1 / (1 + math.exp(-x))
    return s

# **** test the sigmoid function ****
val = basic_sigmoid(3)
#val = basic_sigmoid(0)
print("val: " + str(val))

val: 0.9525741268224334


In [4]:
# **** define a vector (list) ****
x = [1, 2, 3, 4]
#x = np.array([1, 2, 3, 4])
#x = np.array([[1, 2, 3, 4])
print("x: " + str(x))

# **** try the basic_sigmoid function ****
val = basic_sigmoid(x)

x: [1, 2, 3, 4]


TypeError: bad operand type for unary -: 'list'

In [5]:
# **** now let's try it with Numpy ****
import numpy as np

# **** define a numpy vector (array) ****
x = np.array([1, 2, 3, 4])
#x = np.array([[1, 2, 3, 4]])
print("x: " + str(x))
print("x.shape: " + str(x.shape))
print()

# **** compute the exponential of each element in the array ****
val = np.exp(x)
print("val: " + str(val))
print("val.shape: " + str(val.shape))

x: [1 2 3 4]
x.shape: (4,)

val: [ 2.71828183  7.3890561  20.08553692 54.59815003]
val.shape: (4,)


In [6]:
# **** add a constant to each element in the array ****
print("x + 3: " + str(x + 3))

# **** save the results in an array ****
val = x + 3
print("val: " + str(val))
print("val.shape: " + str(val.shape))

x + 3: [4 5 6 7]
val: [4 5 6 7]
val.shape: (4,)


In [7]:
# **** get quick access to documentation on a numpy function ****
np.exp?

In [8]:
# **** sigmoid function using Numpy definition ****
def sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

# **** try the sigmoid function ****
print("x: " + str(x))
val = sigmoid(x)
print("sigmoid(x): " + str(val))
print("val.shape: " + str(val.shape))

x: [1 2 3 4]
sigmoid(x): [0.73105858 0.88079708 0.95257413 0.98201379]
val.shape: (4,)


In [9]:
# **** sigmoid_derivative function definition ****
def sigmoid_derivative(x):
    s = sigmoid(x)
    ds = s * (1 - s)
    return ds

# **** try the sigmoid_derivative function ****
x = np.array([1, 2, 3, 4])
print("x: " + str(x))
val = sigmoid_derivative(x)
print("sigmoid_derivative(x): " + str(val))
print("val.shape: " + str(val.shape))

x: [1 2 3 4]
sigmoid_derivative(x): [0.19661193 0.10499359 0.04517666 0.01766271]
val.shape: (4,)


In [10]:
# **** define an extremely small RGB image ****

#image = np.random.randn(3, 3, 2)
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print("image:\n" + str(image))
print()

print("image.shape: " + str(image.shape))
print("image.shape[0]: " + str(image.shape[0]))
print("image.shape[1]: " + str(image.shape[1]))
print("image.shape[2]: " + str(image.shape[2]))

image:
[[[0.67826139 0.29380381]
  [0.90714982 0.52835647]
  [0.4215251  0.45017551]]

 [[0.92814219 0.96677647]
  [0.85304703 0.52351845]
  [0.19981397 0.27417313]]

 [[0.60659855 0.00533165]
  [0.10820313 0.49978937]
  [0.34144279 0.94630077]]]

image.shape: (3, 3, 2)
image.shape[0]: 3
image.shape[1]: 3
image.shape[2]: 2


In [11]:
# **** image2vector function definition ****
def image2vector(image):
    v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    return v

# **** try the image2vector function ****
x = image2vector(image)
print("image2vector(image):\n" + str(x))
print("x.shape: " + str(x.shape))

image2vector(image):
[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
x.shape: (18, 1)


In [12]:
# **** normalizeRows function definition ****
def normalizeRows(x):
    
    # **** compute the norm per row ****
    x_norm = np.linalg.norm(x, ord = 2, axis = 1, keepdims = True)
    print("x_norm:\n" + str(x_norm))
    print("x_norm.shape: " + str(x_norm.shape))

    x_norm_0 = np.sqrt((x ** 2).sum(axis = 1, keepdims = True))
    print("x_norm_0:\n" + str(x_norm_0))
    
    x = x / x_norm
    return x

# **** define an array to normalize ****
x = np.array([[0, 3, 4],
              [1, 6, 4]])
print("x.shape: " + str(x.shape))
print()

val = normalizeRows(x)
print()

print("normalizeRows(x):\n" + str(val))

x.shape: (2, 3)

x_norm:
[[5.        ]
 [7.28010989]]
x_norm.shape: (2, 1)
x_norm_0:
[[5.        ]
 [7.28010989]]

normalizeRows(x):
[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [13]:
# **** define softmax function ****
def softmax(x):
    # **** apply exp() element-wise to x ****
    x_exp = np.exp(x)
#    print("x_exp.shape: " + str(x_exp.shape))
    
    # **** create a vector x_sum that sums each row of x_exp ****
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
#    print("x_sum.shape: " + str(x_sum.shape))
    
    # **** compute the softmax(x) by dividing x_exp by x_sum (broadcasting in action) ****
    s = x_exp / x_sum
    
    return s

# **** define an array to compute the softmax ****
x = np.array([[9, 2, 5, 0, 0],
              [7, 5, 0, 0, 0]])
val = softmax(x)
print()

print("softmax(x):\n" + str(val))
print("val.shape: " + str(val.shape))


softmax(x):
[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
val.shape: (2, 5)


In [14]:
# **** to time operations ****
import time

# **** arrays to use for testing vectorization ****
#x1 = np.random.randn(15000)
#x2 = np.random.randn(15000)

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]
print("type(x1): " + str(type(x1)))
print("len(x1): " + str(len(x1)))

#x1 = np.array([9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0])
#x2 = np.array([9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0])
#print("type(x1): " + str(type(x1)))
#print("x1.shape: " + str(x1.shape))

# **** clasic dot product of vectors ****
tic = time.process_time_ns()
dot = 0
for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time_ns()
print(" dot: " + str(dot))
print("time: " + str(toc - tic) + " ns")
print()

# **** classic outer product of vectors ****
tic = time.process_time_ns()

#print("len(x1): " + str(len(x1)))
#print("len(x2): " + str(len(x2)))

outer = np.zeros((len(x1), len(x2)))
#print("outer.shape: " + str(outer.shape))

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i, j] = x1[i] * x2[j]
toc = time.process_time_ns()
print("outer:\n" + str(outer))
print("time: " + str(toc - tic) + " ns")
print()

# **** classic elementwise multiplication ****
tic = time.process_time_ns()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time_ns()
print("mul:\n" + str(mul))
print("time: " + str(toc - tic) + " ns")
print()

# **** classic general dot product implementation ****
W = np.random.randn(3, len(x1))
print("W:\n" + str(W))
tic = time.process_time_ns()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i, j] * x1[j]
toc = time.process_time_ns()
print("gdot:\n" + str(gdot))
print("time: " + str(toc - tic) + " ns")
print()

type(x1): <class 'list'>
len(x1): 15
 dot: 278
time: 0 ns

outer:
[[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [15]:
# **** vectorized dot product ****
tic = time.process_time_ns()
dot = np.dot(x1, x2)
toc = time.process_time_ns()
print(" dot: " + str(dot))
print("time: " + str(toc - tic) + " ns")
print()

# **** vectorized outer product of vectors ****
tic = time.process_time_ns()
outer = np.outer(x1, x2)
toc = time.process_time_ns()
print("outer:\n" + str(outer))
print("time: " + str(toc - tic) + " ns")
print()

# **** vectorized elementwise multiplication ****
tic = time.process_time_ns()
mul = np.multiply(x1, x2)
toc = time.process_time_ns()
print("mul:\n" + str(mul))
print("time: " + str(toc - tic) + " ns")
print()

# **** vectorized general dot product ****
tic = time.process_time_ns()
gdot = np.dot(W, x1)
toc = time.process_time_ns()
print("gdot:\n" + str(gdot))
print("time: " + str(toc - tic) + " ns")
print()

 dot: 278
time: 0 ns

outer:
[[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
time: 0 ns

mul:
[81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
time: 0 ns

gdot:
[ 11.52534544  -6.45689054 -16.21872719]
time: 0 ns



In [16]:
# **** define L1 loss function ****
def L1(yhat, y):
    loss = np.sum(np.abs(y - yhat))
    return loss

# **** test the L1 loss function ***
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
val = L1(yhat, y)
print("L1: " + str(val))

L1: 1.1


In [17]:
# **** define the L2 loss function ****
def L2(yhat, y):
#    loss = np.sum(np.square(y - yhat))
    loss = np.sum(np.dot(y - yhat, y - yhat))
    return loss

# *** test the L2 loss function ****
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
val = L2(yhat, y)
print("L2: " + str(val))


L2: 0.43000000000000005
